#!/bin/bash
set -e

# Name for the output files
TAR_NAME="zipscripts2.0.tar.gz"
OUT_PS1="self_extracting_zipScript.ps1"

# Create tar.gz of the current directory, excluding the output files themselves
tar --exclude="$TAR_NAME" --exclude="$OUT_PS1" -czf "$TAR_NAME" .

# Base64 encode the tarball
BASE64_TAR=$(base64 -w 0 -i "$TAR_NAME")

# Create the PowerShell self-extracting script
cat > "$OUT_PS1" <<'EOF'
# Self-extracting PowerShell script generated by make_self_extracting.sh
$ErrorActionPreference = "Stop"
$tarFile = "$env:TEMP\zipscripts2.0.tar.gz"
$base64 = @"
EOF

# Append the base64 tarball
echo "$BASE64_TAR" >> "$OUT_PS1"

cat >> "$OUT_PS1" <<'EOF'
"@
[IO.File]::WriteAllBytes($tarFile, [Convert]::FromBase64String($base64))
Write-Host "Extracting archive to current directory..."
# Extract using tar (Windows 10+ includes tar)
tar -xzf $tarFile -C .
Remove-Item $tarFile
Write-Host "Running zipScript.ps1..."
powershell.exe -ExecutionPolicy Bypass -File ".\zipScript.ps1"
EOF

echo "Self-extracting PowerShell script created: $OUT_PS1"